### ISSUE TITLE
Needs a .deb file to install

### ISSUE THREAD

**Issue by Almaz** [tiktaalik-dev/blueproximity#15]
Please make a .deb file to install on most popular systems.

**Comment by tiktaalik-dev** [comment]
Hi Almaz,

Sorry for the late reply.
Sadly, I don't know yet how to create a .deb package and don't really have much time to research that right now. You're welcome to try :-)
Anyway, I did create an AppImage package that actually do what you want: Running BlueProximity anywhere, on any distro, without worrying about installing it. Give it a go!
You can find the AppImage on the page for the [last Release (v1.3.3)](https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3)

Hope that helps.

Cheers,
Rigo
