### ISSUE TITLE
Error when clicking on use selected device

### ISSUE THREAD

**Issue by rxng** [tiktaalik-dev/blueproximity#17]
Traceback (most recent call last):
  File "proximity.py", line 830, in btnSelect_clicked
    self.wTree.get_widget("entryMAC").set_text(mac)
AttributeError: 'Builder' object has no attribute 'get_widget'

**Comment by tiktaalik-dev** [comment]
Hi @rxng,

Sorry for the late reply!
That looks like you may be missing some dependencies. The README file lists what you need to install before launching BlueProximity.
Also, I made available an AppImage package that includes all the required dependencies in a convenient, self-contained executable file. That might be your best option, please try it and let me know how it went. You can find it along with the last release here: [https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3](https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3)

Cheers,
Rodrigo Gambra
[Tiktaalik Dev](https://tiktaalik.dev)

**Comment by tiktaalik-dev** [comment]
I'm closing this issue as it has no new activity after my reply. In case you have something else to report, please feel free to reopen it. Cheers.
